--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 17.5

-- Started on 2025-06-19 21:15:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 51831)
-- Name: product_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_type (
    product_type_name text
);


ALTER TABLE public.product_type OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 51826)
-- Name: sales_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sales_order (
    order_id text,
    order_type text,
    description text,
    product_type_name text,
    customer_id text,
    quantity text,
    order_date text
);


ALTER TABLE public.sales_order OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 51861)
-- Name: st_mapping_set_detail_v3; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.st_mapping_set_detail_v3 (
    row_id integer NOT NULL,
    set_id text,
    pair_id text,
    leftattribute text,
    leftattributevalue text,
    leftattributeid text,
    rightattribute text,
    rightattributevalue text,
    righttattributeid text,
    matchrating text,
    mapby text,
    activeflag text,
    specificvsgeneral text,
    reviewedby text,
    predicate text,
    tranform_type text,
    tranform_program text,
    transform_lookupset text,
    tranform_formula text
);


ALTER TABLE public.st_mapping_set_detail_v3 OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 51860)
-- Name: st_mapping_set_detail_v3_row_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.st_mapping_set_detail_v3 ALTER COLUMN row_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.st_mapping_set_detail_v3_row_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 51801)
-- Name: st_mapping_set_v3; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.st_mapping_set_v3 (
    set_id text NOT NULL,
    setname text,
    pair_id text,
    mappingname text,
    description text,
    leftmodel text,
    leftdatabase text,
    lefttable text,
    leftattribute text,
    maptype text,
    maptype_reverse text,
    mapsubtype text,
    rightmodel text,
    rightdatabase text,
    righttable text,
    rightattribute text,
    tranform_type text,
    tranform_program text,
    transform_lookupset text,
    tranform_formula text,
    active_flag text,
    create_date text,
    update_date text,
    created_by text,
    updated_by text,
    source_instance text,
    sync_flag text,
    sync_status text,
    sync_date text,
    batch_id text,
    org_id text,
    related_row_id text,
    valuemaplogic1 text,
    valuemaplogic2 text,
    commfromtable text,
    commfromattribute text,
    src1 text,
    src1val text,
    src2 text,
    src2val text,
    src3 text,
    src3val text,
    src4 text,
    src4val text,
    src5 text,
    src5val text,
    src6 text,
    src6val text,
    src7 text,
    src7val text,
    fromdatatype text,
    commtotable text,
    commtoattribute text,
    trg1 text,
    trg1val text,
    trg2 text,
    trg2val text,
    trg3 text,
    trg3val text,
    trg4 text,
    trg4val text,
    trg5 text,
    trg5val text,
    trg6 text,
    trg6val text,
    trg7 text,
    trg7val text,
    todatatype text,
    qry_sqlfile1_actual text,
    qry_sqlfile2_actual text
);


ALTER TABLE public.st_mapping_set_v3 OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 51843)
-- Name: st_schema_attribute; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.st_schema_attribute (
    schema_attribute_key text NOT NULL,
    schema_table_key text,
    tablename text,
    tableattribute text,
    data_type text
);


ALTER TABLE public.st_schema_attribute OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 51836)
-- Name: st_schema_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.st_schema_table (
    schema_table_key text NOT NULL,
    schema_key text,
    tablename text
);


ALTER TABLE public.st_schema_table OWNER TO postgres;

--
-- TOC entry 4859 (class 0 OID 51831)
-- Dependencies: 217
-- Data for Name: product_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_type (product_type_name) FROM stdin;
laptop
desktop
server
\.


--
-- TOC entry 4858 (class 0 OID 51826)
-- Dependencies: 216
-- Data for Name: sales_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sales_order (order_id, order_type, description, product_type_name, customer_id, quantity, order_date) FROM stdin;
ord1	retail	new order	laptop	c1	200	2025-04-25
\.


--
-- TOC entry 4863 (class 0 OID 51861)
-- Dependencies: 221
-- Data for Name: st_mapping_set_detail_v3; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.st_mapping_set_detail_v3 (row_id, set_id, pair_id, leftattribute, leftattributevalue, leftattributeid, rightattribute, rightattributevalue, righttattributeid, matchrating, mapby, activeflag, specificvsgeneral, reviewedby, predicate, tranform_type, tranform_program, transform_lookupset, tranform_formula) FROM stdin;
3	set1	\N	product_type_name		\N	item_type_name		\N			\N	\N	mtp	\N	lookupset	\N	set2	\N
4	set2	\N		laptop	\N		handheld	\N	100	algorithm	\N	\N	mtp	\N		\N		\N
\.


--
-- TOC entry 4857 (class 0 OID 51801)
-- Dependencies: 215
-- Data for Name: st_mapping_set_v3; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.st_mapping_set_v3 (set_id, setname, pair_id, mappingname, description, leftmodel, leftdatabase, lefttable, leftattribute, maptype, maptype_reverse, mapsubtype, rightmodel, rightdatabase, righttable, rightattribute, tranform_type, tranform_program, transform_lookupset, tranform_formula, active_flag, create_date, update_date, created_by, updated_by, source_instance, sync_flag, sync_status, sync_date, batch_id, org_id, related_row_id, valuemaplogic1, valuemaplogic2, commfromtable, commfromattribute, src1, src1val, src2, src2val, src3, src3val, src4, src4val, src5, src5val, src6, src6val, src7, src7val, fromdatatype, commtotable, commtoattribute, trg1, trg1val, trg2, trg2val, trg3, trg3val, trg4, trg4val, trg5, trg5val, trg6, trg6val, trg7, trg7val, todatatype, qry_sqlfile1_actual, qry_sqlfile2_actual) FROM stdin;
set1	\N	\N	\N	\N	model1	test_etl_db1	sales_order		schema to schema	\N	\N	model2	test_etl_db2	sales_txn		\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
set2	\N	\N	\N	\N	model1	test_etl_db1	product_type	product_type_name	category to category	\N	\N	model2	test_etl_db2	item_type	item_type_name	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N
\.


--
-- TOC entry 4861 (class 0 OID 51843)
-- Dependencies: 219
-- Data for Name: st_schema_attribute; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.st_schema_attribute (schema_attribute_key, schema_table_key, tablename, tableattribute, data_type) FROM stdin;
\.


--
-- TOC entry 4860 (class 0 OID 51836)
-- Dependencies: 218
-- Data for Name: st_schema_table; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.st_schema_table (schema_table_key, schema_key, tablename) FROM stdin;
\.


--
-- TOC entry 4869 (class 0 OID 0)
-- Dependencies: 220
-- Name: st_mapping_set_detail_v3_row_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.st_mapping_set_detail_v3_row_id_seq', 4, true);


--
-- TOC entry 4709 (class 2606 OID 51807)
-- Name: st_mapping_set_v3 st_mapping_set_v3_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_mapping_set_v3
    ADD CONSTRAINT st_mapping_set_v3_pkey PRIMARY KEY (set_id);


--
-- TOC entry 4713 (class 2606 OID 51849)
-- Name: st_schema_attribute st_schema_attribute_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_schema_attribute
    ADD CONSTRAINT st_schema_attribute_pkey PRIMARY KEY (schema_attribute_key);


--
-- TOC entry 4711 (class 2606 OID 51842)
-- Name: st_schema_table st_schema_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_schema_table
    ADD CONSTRAINT st_schema_table_pkey PRIMARY KEY (schema_table_key);


-- Completed on 2025-06-19 21:15:57

--
-- PostgreSQL database dump complete
--

